IBM/networking-node-sdk

- README.md
- package.json
Updated ReadMe and package.json with proper URLs
> (docs): Updated the package json and readme with proper URLs

- package.json
> (chore): updated the version

- .travis.yml
- package.json
> fix(build): add npm deployment to build

- .gitignore
> feat(build): Build the first minor version

- direct-link/v1.ts
- test/integration/direct-link.v1.test.js
- test/unit/direct-link.v1.test.js
added the support for macsec enabled gateway
> feat: added the support for macsec enabled gateway

- direct-link/v1.ts
- test/unit/direct-link.v1.test.js
updated the macsec fields as per latest api spec
> fix: updated the macsec fields as per latest api spec

- direct-link/v1.ts
- test/integration/transit-gateway.v1.test.js
- test/unit/direct-link.v1.test.js
deprecated the bgp_base_cidr in direct link
> fix: deprecated the bgp_base_cidr in direct link

- package-lock.json
- package.json
Updated dependencies for security advisories
**Fixes:** 
https://github.com/IBM/networking-node-sdk/pull/24
https://github.com/IBM/networking-node-sdk/pull/23
https://github.com/IBM/networking-node-sdk/pull/22
https://github.com/IBM/networking-node-sdk/pull/21
https://github.com/IBM/networking-node-sdk/pull/15
> fix: Dependabot updates

- dns-svcs/v1.ts
- test/integration/cis/global-load-balancer.v1.test.js
- test/integration/dns-svcs.v1.test.js
- test/unit/dns-svcs.v1.test.js
> feat(Custom Resolver):Added sdk for custom resolver

- .travis.yml
- test/unit/transit-gateway-apis.v1.test.js
- transit-gateway-apis/v1.ts
Support for directlink type transit gateway connection
- [X ] Feature
- [X ] No
> feat: Support for directlink connection type

- .travis.yml
- direct-link-provider/v2.ts
- direct-link/v1.ts
- test/integration/direct-link-provider.v2.test.js
- test/integration/direct-link.v1.test.js
- test/integration/dns-svcs.v1.test.js
- test/unit/direct-link-provider.v2.test.js
- test/unit/direct-link.v1.test.js
implement the changes to edit the BGP Parameters - IPs and ASN
implement the changes to enable/update the BFD config
> feat(DirectLink): add the changes to updated BGP parameters - IP and ASN, Also enable/edit the BFD parameters

- .travis.yml
- README.md
- package-lock.json
- package.json
The Node SDK needed to be updated per latest updates in sdk-core templates.
**Fixes:** https://github.ibm.com/CloudEngineering/node-sdk-template/pull/62
Totally functional.
Totally functional.
This PR removes codecov from the project entirely
> fix: Updated Node SDK per latest updates in sdk-core templates.

- cis/alertsv1/v1.ts
- cis/firewallrulesv1/v1.ts
- cis/webhooksv1/v1.ts
- test/integration/cis/alerts.v1.test.js
- test/integration/cis/firewall-rules.v1.test.js
- test/integration/cis/webhooks.v1.test.js
- test/integration/dns-svcs.v1.test.js
- test/unit/cis/alerts.v1.test.js
- test/unit/cis/firewall-rules.v1.test.js
- test/unit/cis/webhooks.v1.test.js
> feat(CIS: Alerts, Webhooks): added sdk for alerts and webhooks

- .secrets.baseline
> chore: remove secrets

- package-lock.json
- package.json
- test/integration/transit-gateway.v1.test.js
Address dependency vulnerabilities
> chore: Address Minimist and other vulnerabilities

- dns-svcs/v1.ts
- test/integration/dns-svcs.v1.test.js
- test/integration/transit-gateway.v1.test.js
- test/unit/dns-svcs.v1.test.js
- test/unit/transit-gateway-apis.v1.test.js
- transit-gateway-apis/v1.ts
> Chore : update location order of custom resolver

- dns-svcs/v1.ts
- test/integration/dns-svcs.v1.test.js
- test/unit/dns-svcs.v1.test.js
> feat(secondary zone): added secondary zone

- direct-link/v1.ts
- directlink.env.properties
- package-lock.json
- test/integration/direct-link.v1.test.js
- test/unit/direct-link.v1.test.js
Added `Gateway AS Prepends` endpoints to SDK,
- List AS prepends
- Replace existing AS prepends
> feat(as prepends): added as prepends to direct link

- cis/authenticated-origin-pull-apiv1/v1.ts
- test/integration/cis/authenticated-origin-pull-api.v1.test.js
- test/unit/cis/authenticated-origin-pull-api.v1.test.js
feat: Authenticated Origin Pull
> feat(authOriginPull): adding authenticated origin pull

- direct-link/v1.ts
- test/integration/direct-link.v1.test.js
- test/unit/direct-link.v1.test.js
> feat: added DL BGP Route Filtering

- .travis.yml
dependency: none
Bumping up node versions
**Fixes:** Just a standard node version update
> chore: bumping up node versions

- README.md
> feat: re-triggering the build

- test/integration/dns-svcs.v1.test.js
This PR is created to trigger a release
> feat: PDNS feature release

- .travis.yml
> feat: direct link changes build releases

- .travis.yml
> feat: direct link changes build release

- test/unit/transit-gateway-apis.v1.test.js
- transit-gateway-apis/v1.ts
dependency: none
Regenerated the transit files to introduce Redundant GRE related changes. 
**Fixes:** https://github.ibm.com/CloudBBS/ts-planning/issues/5244
> feat: Added the new connection type - Redundant GRE

- package-lock.json
- package.json
Reverts IBM/networking-node-sdk#136 reverting this PR as the integration tests are failing
> Revert "fix: Updating ibm-cloud-sdk-core npm package version to fix vulnerability"

- .travis.yml
- direct-link/v1.ts
- package-lock.json
- package.json
- test/integration/direct-link.v1.test.js
- test/unit/direct-link.v1.test.js
**Fixes:** [CloudBBS/planning#14587](https://github.ibm.com/CloudBBS/planning/issues/14587)
> feat: direct link macsec changes
